---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - image: geerlingguy/docker-ubuntu2204-ansible
            tag: latest
          - image: geerlingguy/docker-rockylinux9-ansible
            tag: latest
          - image: rsprta/opensuse-ansible
            tag: latest
    steps:
      - name: checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@d3e37309fc9c287d6a3507d172520d37df0e2dda # 6.0.1
        with:
          options: parallel
          scenario: default
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
