---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - image: geerlingguy/docker-ubuntu2204-ansible
            tag: latest
          - image: geerlingguy/docker-ubuntu2404-ansible
            tag: latest
          - image: geerlingguy/docker-debian12-ansible
            tag: latest
          - image: geerlingguy/docker-debian13-ansible
            tag: latest
          - image: geerlingguy/docker-rockylinux9-ansible
            tag: latest
          - image: geerlingguy/docker-fedora40-ansible
            tag: latest
          - image: rsprta/opensuse-ansible
            tag: latest
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@d3e37309fc9c287d6a3507d172520d37df0e2dda # 6.0.1
        with:
          options: parallel
          scenario: default
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
        env:
          ANSIBLE_REMOTE_TMP: /tmp/.ansible
